version: "3"

services:
  redis:
    image: redis:6.2.3
    container_name: redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: ${MACHINE_ID}  # ZK 集群中本容器的唯一编号
      ZOO_SERVERS: ${ZOO_SERVERS}  # ZK 集群中所有实例的逗号分隔列表
      KAFKA_DELETE_TOPIC_ENABLE: "true"  # 允许删除 topic
  kafka:
    image: schrbr/kafka:2.13-2.6.0
    container_name: kafka
    restart: always
    volumes:
      - ./kafka:/data/kafka
    ports:
      - 9092:9092
      - 1099:1099
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${MACHINE_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOO_CONNECT}
      KAFKA_ADVERTISED_HOST_NAME: ${SERVER_IP}
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_JMX_OPTS: -Djava.rmi.server.hostname=${SERVER_IP} -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=1099
      JMX_PORT: 1099
  kafkamanager:
    image: scjtqs/kafka-manager
    container_name: kafkamanager
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: ${ZOO_CONNECT}
      APPLICATION_SECRET: letmein
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: ${KAFKA_MANAGER_USERNAME}
      KAFKA_MANAGER_PASSWORD: ${KAFKA_MANAGER_PASSWORD}
  mysql:
    image: biarms/mysql:5.7.33-beta-circleci
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
  phpmyadmin:
    image: phpmyadmin:5.1.0
    container_name: myadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
