version: "3"

services:
  redis:
    image: redis:6.2.3
    container_name: redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data/kafka
  zookeeper:
    image: cfei/zookeeper:latest-multiarch
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1  # ZK 集群中本容器的唯一编号
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888  # ZK 集群中所有实例的逗号分隔列表
  kafka:
    image: cfei/kafka:latest-multiarch
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./data/kafka:/data/kafka
    environment:
      KAFKA_BROKER_ID: 1  # Kafka 集群中本容器的唯一编号
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181  # Kafka 将连接到的 Zookeeper URI 的逗号分隔列表
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
    depends_on:
      - zookeeper